language: node_js
node_js:
  - '4.2.2'
before_script:
  - 'export CHROME_BIN=chromium-browser'
  - 'export DISPLAY=:99.0'
  - 'sh -e /etc/init.d/xvfb start'
  - 'npm install -g bower karma grunt-cli jshint codecov codeclimate-test-reporter'
  - 'npm install' # install npm packages
  - 'bower install' # install bower packages

after_script:
  - 'grunt default'
  - 'codecov coverage/cobertura/cobertura-coverage.xml --token=0e9a0ba9-bf88-4288-aa9d-3cd9bdf17df2'
  - 'CODECLIMATE_REPO_TOKEN=83d641cc530668f3afe1a2f7745497e67153b969acbddbb1dbf06af023df241b codeclimate-test-reporter < coverage/lcov/lcov.info'
